// --- DEFINIÇÃO DOS TIPOS ---
export type CategoryType = "todos" | "decoracao" | "estatuas" | "amuletos";

export interface Artifact {
  id: string;
  title: string;
  imageSrc: string;
  amazonLink: string;
  category: CategoryType;
}

// --- LISTA DE DADOS ---
// Cole a lista completa de artefatos aqui dentro
export const ARTIFACTS: Artifact[] = [
  // --- DECORAÇÃO ---
{
    id: "d1",
    title: "Pirâmide Energética em Cobre De Vidro (Kit 3)",
    imageSrc: "https://m.media-amazon.com/images/I/51SY0dwsfpL._AC_SL1000_.jpg", 
    amazonLink: "https://amzn.to/3NmSOj2",
    category: "decoracao",
  },
  {
    id: "d2",
    title: "Pyramid Ogan Crystal Energy Tower",
    imageSrc: "https://m.media-amazon.com/images/I/51jxHltjaoS._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/49XgEKL",
    category: "decoracao",
  },
  {
    id: "d3",
    title: "Molde de Silicone Pirâmide (Artesanato)",
    imageSrc: "https://m.media-amazon.com/images/I/61G-LeJInpL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/45PNk6r",
    category: "decoracao",
  },
  {
    id: "d4",
    title: "Estatueta de Pirâmide de Cristal",
    imageSrc: "https://m.media-amazon.com/images/I/61OTLgYXITL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/3NpdNBC",
    category: "decoracao",
  },
  {
    id: "d5",
    title: "Luminária LED Bola de Cristal 3D (Base Madeira)",
    imageSrc: "https://m.media-amazon.com/images/I/712WKEpj9VL._AC_SX342_SY445_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4sDQ5BT",
    category: "decoracao",
  },
  {
    id: "d6",
    title: "Globo Terrestre Decorativo Base Metálica",
    imageSrc: "https://m.media-amazon.com/images/I/61XkgiARFCL._AC_SL1000_.jpg", 
    amazonLink: "https://amzn.to/4r1GlzP",
    category: "decoracao",
  },
  {
    id: "d7",
    title: "Pêndulo Cinético",
    imageSrc: "https://m.media-amazon.com/images/I/51yXDr2czUL._AC_SL1200_.jpg", 
    amazonLink: "https://amzn.to/4sJgqOW",
    category: "decoracao",
  },
  {
    id: "d8",
    title: "Suporte de Vela Giratório Dourado",
    imageSrc: "https://m.media-amazon.com/images/I/51ksONz5MoL._AC_SL1080_.jpg", 
    amazonLink: "https://amzn.to/3ZddfRQ",
    category: "decoracao",
  },
  {
    id: "d9",
    title: "Ampulheta Torre Eiffel",
    imageSrc: "https://m.media-amazon.com/images/I/61GwGQPwCKL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/3YGVx9i",
    category: "decoracao",
  },
  {
    id: "d10",
    title: "Escultura Pêndulo de Newton",
    imageSrc: "https://m.media-amazon.com/images/I/61G1v++BDwL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4qiW8tX",
    category: "decoracao",
  },
  {
    id: "d11",
    title: "Luminária Bola de Cristal 3D",
    imageSrc: "https://m.media-amazon.com/images/I/61Fx5mWHN4L._AC_SX342_SY445_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4pESidi",
    category: "decoracao",
  },
  {
    id: "d12",
    title: "Kit 2 Abajur Lua Cheia",
    imageSrc: "https://m.media-amazon.com/images/I/5141JV9ubBL._AC_SX342_SY445_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4jKwn39",
    category: "decoracao",
  },
  {
    id: "d13",
    title: "Fonte Estátua de Dragão de Jardim",
    imageSrc: "https://m.media-amazon.com/images/I/71EDz2DawXL._AC_SL1002_.jpg", 
    amazonLink: "https://amzn.to/4sCuOZ7",
    category: "decoracao",
  },
  {
    id: "d14",
    title: "Torre Eiffel Decorativa",
    imageSrc: "https://m.media-amazon.com/images/I/512tHDTFJyL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/3LK7aJE",
    category: "decoracao",
  },
  {
    id: "d15",
    title: "Casa de João de Barro Decorativa",
    imageSrc: "https://m.media-amazon.com/images/I/41k9btxFZCL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/45egR9S",
    category: "decoracao",
  },
  {
    id: "d16",
    title: "Balança Decorativa da Justiça Dourada",
    imageSrc: "https://m.media-amazon.com/images/I/41VWyzJ8mrL._SX342_SY445_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4jESPuy",
    category: "decoracao",
  },

  // --- ESTÁTUAS & ÍDOLOS ---
  {
    id: "s1",
    title: "Estátua Decorativa da Justiça",
    imageSrc: "https://m.media-amazon.com/images/I/61ysTuJ4OiL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4jSbnrl",
    category: "estatuas",
  },
  {
    id: "s2",
    title: "Estátua Elefante da Sorte Feng Shui",
    imageSrc: "https://m.media-amazon.com/images/I/81oURGNO9HL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4bkJrdF",
    category: "estatuas",
  },
  {
    id: "s3",
    title: "Estátua Elefante Riqueza Sorte",
    imageSrc: "https://m.media-amazon.com/images/I/71mvrcDYMKL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4qVYLlp",
    category: "estatuas",
  },
  {
    id: "s4",
    title: "Escultura Sucellus Deus Celta",
    imageSrc: "https://m.media-amazon.com/images/I/61a2veFNAfL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4qURodO",
    category: "estatuas",
  },
  {
    id: "s5",
    title: "Escultura Leopardo Dourado",
    imageSrc: "https://m.media-amazon.com/images/I/71X+JXh5MKL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/3NNP9us",
    category: "estatuas",
  },
  {
    id: "s6",
    title: "Escultura Decorativa de Águia",
    imageSrc: "https://m.media-amazon.com/images/I/71mbRd0YpEL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/3LONPHc",
    category: "estatuas",
  },
  {
    id: "s7",
    title: "Estatueta Gato Bruxo Wicca",
    imageSrc: "https://m.media-amazon.com/images/I/61-uahf2JmL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/45Hd3Ow",
    category: "estatuas",
  },
  {
    id: "s8",
    title: "Olho De Hórus Egito",
    imageSrc: "https://m.media-amazon.com/images/I/71TLzS0t3oL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/3LK86xE",
    category: "estatuas",
  },
  {
    id: "s9",
    title: "Estátua Afrodite",
    imageSrc: "https://m.media-amazon.com/images/I/61F8Ng6bloL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/49FWQdN",
    category: "estatuas",
  },
  {
    id: "s10",
    title: "Estátua da Águia Dourada",
    imageSrc: "https://m.media-amazon.com/images/I/819D4jTA6iL._AC_SL1500_.jpg", 
    amazonLink: "https://amzn.to/3NLSUR7",
    category: "estatuas",
  },
  {
    id: "s11",
    title: "Divino Espírito Santo",
    imageSrc: "https://m.media-amazon.com/images/I/71EHJbNJYtL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4qkTmEp",
    category: "estatuas",
  },
  {
    id: "s12",
    title: "Valquiria A Guerreira Nórdica",
    imageSrc: "https://m.media-amazon.com/images/I/71enOF1+4KL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4qpBmsM",
    category: "estatuas",
  },
  {
    id: "s13",
    title: "Ulisses e Cão Argos (Odisseia)",
    imageSrc: "https://m.media-amazon.com/images/I/51xFr8zEA6L._AC_SX466_.jpg", 
    amazonLink: "https://amzn.to/3LCtbKq",
    category: "estatuas",
  },
  {
    id: "s14",
    title: "Mago Merlin De Monte Moore",
    imageSrc: "https://m.media-amazon.com/images/I/71Of3+nxHVL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/49Y36yI",
    category: "estatuas",
  },
  {
    id: "s15",
    title: "Cronos O Deus Do Tempo",
    imageSrc: "https://m.media-amazon.com/images/I/618YQcJ9HOL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4jFDNVj",
    category: "estatuas",
  },
  {
    id: "s16",
    title: "Coruja Mágica Da Sabedoria",
    imageSrc: "https://m.media-amazon.com/images/I/710YAX4wSVL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/49pO98w",
    category: "estatuas",
  },
  {
    id: "s17",
    title: "Alexandre O Grande",
    imageSrc: "https://m.media-amazon.com/images/I/61wShpXE7PL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/45cavrv",
    category: "estatuas",
  },
  {
    id: "s18",
    title: "Estátua Da Justiça Themis",
    imageSrc: "https://m.media-amazon.com/images/I/51J2Lplk-VL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/3NpkHH2",
    category: "estatuas",
  },
  {
    id: "s19",
    title: "Nike A Deusa Grega Da Vitória",
    imageSrc: "https://m.media-amazon.com/images/I/51DfLfWjsrL._AC_SX300_SY300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4jShwnp",
    category: "estatuas",
  },
  {
    id: "s20",
    title: "Zeus O Senhor Do Universo",
    imageSrc: "https://m.media-amazon.com/images/I/61rahUMLlaL._AC_SY300_SX300_QL70_ML2_.jpg", 
    amazonLink: "https://amzn.to/4bH5Stk",
    category: "estatuas",
  },

  // --- AMULETOS & JOIAS ---
  {
    id: "j1",
    title: "Corrente Masculina Estrela de Davi",
    imageSrc: "https://m.media-amazon.com/images/I/515Q36A0lWL._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/4bzDUzG",
    category: "amuletos",
  },
  {
    id: "j2",
    title: "Amuleto Masculino Ouroboros",
    imageSrc: "https://m.media-amazon.com/images/I/41qu3pG0e-L._AC_SX342_.jpg", 
    amazonLink: "https://amzn.to/49FsGqX",
    category: "amuletos",
  },
  {
    id: "j3",
    title: "Colar Viking Lança de Odin",
    imageSrc: "https://m.media-amazon.com/images/I/51wIqN3mtBL._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/3YDxmbR",
    category: "amuletos",
  },
  {
    id: "j4",
    title: "Colar Proteção Eterna São Bento",
    imageSrc: "https://m.media-amazon.com/images/I/51Wk6Z4i4-L._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/4pEYsKE",
    category: "amuletos",
  },
  {
    id: "j5",
    title: "Amuleto Jade Natural Taiji",
    imageSrc: "https://m.media-amazon.com/images/I/61WDF0Wsx0L._AC_SY445_.jpg", 
    amazonLink: "https://amzn.to/49yXo52",
    category: "amuletos",
  },
  {
    id: "j6",
    title: "Pingente São Miguel Arcanjo",
    imageSrc: "https://m.media-amazon.com/images/I/51e0BdfTE1L._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/4sDXQaZ",
    category: "amuletos",
  },
  {
    id: "j7",
    title: "Pingente Obsidiana Negra Hexagonal",
    imageSrc: "https://m.media-amazon.com/images/I/41YFd73zvgL._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/4sJgRbX",
    category: "amuletos",
  },
  {
    id: "j8",
    title: "Conjunto Pulseiras Divine Charm",
    imageSrc: "https://m.media-amazon.com/images/I/61JoH-EjLlL._AC_SX522_.jpg", 
    amazonLink: "https://amzn.to/4qWtFtY",
    category: "amuletos",
  },
  {
    id: "j9",
    title: "Colar Martelo de Thor Mjölnir",
    imageSrc: "https://m.media-amazon.com/images/I/51FKiAJ40KL._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/4bytpg2",
    category: "amuletos",
  },
  {
    id: "j10",
    title: "Colar Feminino Santíssima Trindade",
    imageSrc: "https://m.media-amazon.com/images/I/31cKuKGMjcL._AC_SX342_.jpg", 
    amazonLink: "https://amzn.to/3Lwa6cS",
    category: "amuletos",
  },
  {
    id: "j11",
    title: "Medalhão Selo dos 7 Arcanjos",
    imageSrc: "https://m.media-amazon.com/images/I/41SC0x-IGvL._AC_SX342_.jpg", 
    amazonLink: "https://amzn.to/4qwCcUI",
    category: "amuletos",
  },
  {
    id: "j12",
    title: "Colar Mapa da Fortuna Obsidiana",
    imageSrc: "https://m.media-amazon.com/images/I/61+zPO1W+UL._AC_SX522_.jpg", 
    amazonLink: "https://amzn.to/4sE8TRz",
    category: "amuletos",
  },
  {
    id: "j13",
    title: "Colar Obsidiana Power Wolf",
    imageSrc: "https://m.media-amazon.com/images/I/51Ixeok0M0L._AC_SX425_.jpg", 
    amazonLink: "https://amzn.to/49W8qCF",
    category: "amuletos",
  },
  {
    id: "j14",
    title: "Bracelete Nórdico Valknut",
    imageSrc: "https://m.media-amazon.com/images/I/31TE8hC3WHL._AC_SX679_.jpg", 
    amazonLink: "https://amzn.to/45gKXJL",
    category: "amuletos",
  },
  {
    id: "j15",
    title: "Pulseira Lobo Wolf Energy",
    imageSrc: "https://m.media-amazon.com/images/I/41HFlDqoXlL._AC_SX466_.jpg", 
    amazonLink: "https://amzn.to/49E1VD4",
    category: "amuletos",
  },
  {
    id: "j16",
    title: "Corrente com Pingente de São Bento",
    imageSrc: "https://m.media-amazon.com/images/I/51-Ji2pZnOL._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/49Y4Dos",
    category: "amuletos",
  },
  {
    id: "j17",
    title: "Pulseira Pedras Naturais Olho de Tigre",
    imageSrc: "https://m.media-amazon.com/images/I/31zBaRPsyVL._AC_.jpg", 
    amazonLink: "https://amzn.to/4bytJvg",
    category: "amuletos",
  },
  {
    id: "j18",
    title: "Medalhão Efésios Armor of God",
    imageSrc: "https://m.media-amazon.com/images/I/513c5PPNo7L._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/3ZjZcde",
    category: "amuletos",
  },
  {
    id: "j19",
    title: "Kit Pulseiras King Panther",
    imageSrc: "https://m.media-amazon.com/images/I/417F8vRN-dL._AC_SX342_.jpg", 
    amazonLink: "https://amzn.to/4r1pxJb",
    category: "amuletos",
  },
  {
    id: "j20",
    title: "Colar Triquetra em Aço",
    imageSrc: "https://m.media-amazon.com/images/I/51D7w-gLjyL._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/3Nf7dOb",
    category: "amuletos",
  },
  {
    id: "j21",
    title: "Colar Insígnia do Guerreiro",
    imageSrc: "https://m.media-amazon.com/images/I/51GopiLoS+L._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/4jIm8w9",
    category: "amuletos",
  },
  {
    id: "j22",
    title: "Conjunto Complementar",
    imageSrc: "https://m.media-amazon.com/images/I/41ukBo7GgZL._AC_SX342_.jpg", 
    amazonLink: "https://amzn.to/4jR9nQg",
    category: "amuletos",
  },
  {
    id: "j23",
    title: "Bracelete Viking Iron Heart",
    imageSrc: "https://m.media-amazon.com/images/I/41D1tGjWLgL._AC_SX522_.jpg", 
    amazonLink: "https://amzn.to/3Nlluc1",
    category: "amuletos",
  },
  {
    id: "j24",
    title: "Anel de Gato Ajustável Sweet Dreams",
    imageSrc: "https://m.media-amazon.com/images/I/51NvooxBL0L._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/3NL5b8q",
    category: "amuletos",
  },
  {
    id: "j25",
    title: "Colar Masculino Tritão",
    imageSrc: "https://m.media-amazon.com/images/I/413xg3MlkZL._AC_SX342_.jpg", 
    amazonLink: "https://amzn.to/3LJcv3X",
    category: "amuletos",
  },
  {
    id: "j26",
    title: "Pingente São Jorge Moeda Antiga",
    imageSrc: "https://m.media-amazon.com/images/I/614S+hOKfwL._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/4pCQfqb",
    category: "amuletos",
  },
  {
    id: "j27",
    title: "Pingente Leão de Juda Moeda Antiga",
    imageSrc: "https://m.media-amazon.com/images/I/61hsqrWEMiL._AC_SX385_.jpg", 
    amazonLink: "https://amzn.to/4qTs1ce",
    category: "amuletos",
  },
];